name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v17
        with:
          name: nix-bindings-haskell
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build nix-bindings-sys
        run: nix build .#nix-bindings-sys

      - name: Build nix-bindings
        run: nix build .#nix-bindings

  autotag:
    if: false # disabled for now
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: taiki-e/install-action@parse-changelog

      - uses: sol/haskell-autotag@v1
        id: autotag
        with:
          package-path: ./nix-bindings
          prefix: "v"

      - name: Create release for nix-bindings
        if: steps.autotag.outputs.created
        run: |
          notes=$(parse-changelog --version-format '(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+' nix-bindings/CHANGELOG.md "${{ steps.autotag.outputs.version }}")
          gh release create "${{ steps.autotag.outputs.name }}" --title "${{ steps.autotag.outputs.name }}" --notes "$notes"
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: sol/haskell-autotag@v1
        id: autotag-sys
        with:
          package-path: ./nix-bindings-sys
          prefix: "sys-v"

      - name: Create release for nix-bindings-sys
        if: steps.autotag-sys.outputs.created
        run: |
          notes=$(parse-changelog --version-format '(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+' nix-bindings-sys/CHANGELOG.md "${{ steps.autotag-sys.outputs.version }}")
          gh release create "${{ steps.autotag-sys.outputs.name }}" --title "${{ steps.autotag-sys.outputs.name }}" --notes "$notes"
        env:
          GH_TOKEN: ${{ github.token }}
